In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/bengaluru_house_prices.csv')
df.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [ ]:
#REMOVE THE COL.
df1=df.drop(['area_type','availability','society'],axis='columns')
df1.head(5)

                   location       size total_sqft  bath  balcony   price
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00

In [ ]:
df1.shape

(13320, 6)

In [ ]:
df1.isnull().sum()

location        1
size           16
total_sqft      0
bath           73
balcony       609
price           0
dtype: int64

In [ ]:
#FILL THE NULL VALUES IN THE COL. BATH
df1['bath'] = df1['bath'].fillna(df1['bath'].median())
df1['balcony'] = df1['balcony'].fillna(df1['balcony'].median())
df1.isnull().sum()

location       1
size          16
total_sqft     0
bath           0
balcony        0
price          0
dtype: int64

In [ ]:
df2=df1.dropna().copy()
df2.head()

                   location       size total_sqft  bath  balcony   price
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00

In [ ]:
#CREATE A NEW COL. BHK
df2['bhk'] = df2['size'].apply(lambda x: int(x.split(' ')[0]))
df2.head()

                   location       size total_sqft  bath  balcony   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00    2

In [ ]:
df2['bhk'].unique()

array([ 2,  4,  3,  6,  1,  8,  7,  5, 11,  9, 27, 10, 19, 16, 43, 14, 12,
       13, 18])

In [ ]:
df2['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [ ]:
df2['balcony'].unique()

array([1., 3., 2., 0.])

In [ ]:
#FOR TO HANDLE '1133 - 1384' THIS TYPE OF VALUES REPLACING THEM WITH AVG.
def convert_sqft_to_num(x):
    tokens = x.split('-')
    if len(tokens) == 2:
        return (float(tokens[0])+float(tokens[1]))/2
    try:
        return float(x)
    except:
        return None


df3 = df2.copy()
df3.total_sqft = df3.total_sqft.apply(convert_sqft_to_num)
# df4 = df4[df4.total_sqft.notnull()]
df3.head(2)

                   location       size  total_sqft  bath  balcony   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0      1.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0      3.0  120.00    4

In [ ]:
# CREATE A COL. PRICE PER SQFT

df4 = df3.copy()
df4['price_per_sqft'] = df4['price']*100000/df4['total_sqft']
df4.head()

,location,size,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,4250.000000

In [ ]:
# Har location kitni baar aayi hai
location_stats = df4['location'].value_counts()

# Jo locations 10 ya usse kam baar aayi hain
location_stats_less_than_10 = location_stats[location_stats <= 10]


df4['location'] = df4['location'].apply(
    lambda x: 'other' if x in location_stats_less_than_10 else x
)


df4.head(10)

,location,size,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,4250.000000
5,Whitefield,2 BHK,1170.0,2.0,1.0,38.00,2,3247.863248
6,Old Airport Road,4 BHK,2732.0,4.0,2.0,204.00,4,7467.057101
7,Rajaji Nagar,4 BHK,3300.0,4.0,2.0,600.00,4,18181.818182
8,Marathahalli,3 BHK,1310.0,3.0,1.0,63.25,3,4828.244275
9,other,6 Bedroom,1020.0,6.0,2.0,370.00,6,36274.509804

In [ ]:
df4.shape

(13303, 8)

In [ ]:
df4.to_csv('cleaned_bengaluru_house(01).csv', index=False)

In [ ]:
df4['sqft_per_bhk'] = df4['total_sqft'] / df4['bhk']

df4['sqft_per_bhk'].describe()

count    13257.000000
mean       574.423690
std        387.598667
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
Name: sqft_per_bhk, dtype: float64

In [ ]:
df5 = df4[df4['sqft_per_bhk'] >= 300].copy()

In [ ]:
df5['price_per_sqft'].describe()

count     12513.000000
mean       6307.441644
std        4160.931610
min         267.829813
25%        4210.526316
50%        5295.007564
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [ ]:
def remove_pps_outliers(df):
    df_out = pd.DataFrame()

    for location, subdf in df.groupby('location'):
        mean = np.mean(subdf['price_per_sqft'])
        std = np.std(subdf['price_per_sqft'])

        reduced_df = subdf[
            (subdf['price_per_sqft'] >= mean - std) &
            (subdf['price_per_sqft'] <= mean + std)
        ]

        df_out = pd.concat([df_out, reduced_df], ignore_index=True)

    return df_out
df6 = remove_pps_outliers(df5)

print("Before:", df5.shape)
print("After:", df6.shape)
print("Removed:", df5.shape[0] - df6.shape[0])

Before: (12513, 9)
After: (10289, 9)
Removed: 2224

In [ ]:
def remove_bhk_outliers(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk-1)
            if stats and stats['count']>5:
                exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft<(stats['mean'])].index.values)
    return df.drop(exclude_indices,axis='index')
df8 = remove_bhk_outliers(df6)
# df8 = df7.copy()
df8.shape

(7365, 9)

In [ ]:
df9 = df8[df8.bath<df8.bhk+2]
df9.shape

(7287, 9)

In [ ]:
df10 = df9.drop(['size','price_per_sqft','sqft_per_bhk'],axis='columns')
df10.head(3)

               location  total_sqft  bath  balcony  price  bhk
1   Devarachikkanahalli      1250.0   2.0      2.0   40.0    2
2   Devarachikkanahalli      1200.0   2.0      2.0   83.0    2
3   Devarachikkanahalli      1170.0   2.0      2.0   40.0    2

In [ ]:
dummies = pd.get_dummies(df10['location'], dtype=int)

dummies.head()

,Devarachikkanahalli,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,6th Phase JP Nagar,7th Phase JP Nagar,8th Phase JP Nagar,...,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,other
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df11 = pd.concat([df10, dummies], axis=1)

In [ ]:
dummies = pd.get_dummies(df10['location'], drop_first=True, dtype=int)

df11 = pd.concat([df10.drop('location', axis=1), dummies], axis=1)

df11.head()
df11.shape

(7287, 246)

In [ ]:
X = df11.drop('price', axis=1)
y = df11['price']

print(X.shape)
print(y.shape)

(7287, 245)
(7287,)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)

(5829, 245)
(1458, 245)

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

print("R2 Score:", lr.score(X_test, y_test))

R2 Score: 0.8501980204546077

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

print("Random Forest R2 Score:", rf.score(X_test, y_test))

Random Forest R2 Score: 0.8477671338197386

In [ ]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=100,
    random_state=42
)

xgb.fit(X_train, y_train)

print("XGBoost R2 Score:", xgb.score(X_test, y_test))

XGBoost R2 Score: 0.8114197529360672

In [ ]:
final_model = lr

In [ ]:
import joblib

joblib.dump(final_model, 'house_price_model.pkl')
joblib.dump(list(X.columns), 'model_columns.pkl')

['model_columns.pkl']

In [ ]:
import joblib

locations = sorted(df10["location"].unique())

joblib.dump(locations, "locations.pkl")

['locations.pkl']